Feat/sponsored
2077-Collective/research-rework pull request #17
Opened 2024-10-24 10:10 UTC by losndu

2024-10-25 14:41 UTC, iankressin requested changes

2024-10-25 14:41 UTC, iankressin commented on src/lib/components/ui/ArticleCard.svelte
> +	const TRANSITION_DURATION = 300 as const;
```suggestion
	const TRANSITION_DURATION = 300;
```

You don't need `as const` here, as it's not an object or array. `const` is already enough to make the value immutable

2024-10-25 14:41 UTC, iankressin commented on src/lib/components/ui/ArticleCard.svelte
> +	<div transition:slide={{ duration: TRANSITION_DURATION }} class={`flex flex-col justify-center h-fit ${variant === 'sponsored' ? 'bg-yellow-100 border border-yellow-500' : ''}`}>
This is a valid suggestion. It improves readability and we have this pattern throughout a bunch of components already

2024-10-25 14:41 UTC, iankressin commented on src/lib/components/ui/ArticleList.svelte
> +	}
padding shouldn't be customizable, only card bg and text color

2024-10-25 14:41 UTC, iankressin commented on src/lib/components/ui/ArticleList.svelte
> +						: ''}
```suggestion
					class={`bg-[${validateColor(...)}] text-[${validateColor(...)}]`}
```

Default to `class` instead of `style`

2024-10-25 14:41 UTC, iankressin commented on src/lib/components/ui/ArticleList.svelte
> +	}
should also remove from backend

2024-10-25 14:41 UTC, iankressin commented on src/lib/types/article.ts
> +const paddingRegex = /^(p[txbylr](-[0-9]+)?\s*)+$/;
Export these variables from this file and import from `ArticleCard`

2024-10-25 14:41 UTC, iankressin commented on src/lib/components/ui/ArticleList.svelte
> +	}
You don't need to validate the color here again, you're already doing that in the `SponsorFieldsSchema`

2024-10-25 14:41 UTC, iankressin commented on src/lib/types/article.ts
> +export const ArticleMetadataArraySchema = z.array(ArticleMetadataSchema);
nice

2024-10-25 14:41 UTC, iankressin commented on README.md
This should've been done on its own PR. It has nothing to do with the sponsor card.

You can leave here for this PR, but create separate PR for different scopes next time.

Before submitting your PRs, give it a review and reflect if all the changes  being proposed are within the same scope.

2024-10-25 14:41 UTC, iankressin commented on README.md
> +| VITE_API_BASE_URL | Base URL for API endpoints | http://localhost:3000/api |
This is a valid comment. You used port 8000 on `.env.example` and 3000 here

2024-10-25 14:41 UTC, iankressin commented on README.md
> +| VITE_API_BASE_URL | Base URL for API endpoints | http://localhost:3000/api |
These comments shouldn't be dismissed without a reason.

From now on, if you're dismissing a comment, please leave a comment explaining why

2024-10-25 14:41 UTC, iankressin commented on README.md
> +cd <project-directory>
This is a valid comment

2024-10-25 14:41 UTC, iankressin commented on README.md
> +    ```cp .env.example .env```
This is a valid comment

2024-10-27 15:25 UTC, losndu commented on README.md
Ok, noted

2024-10-28 04:39 UTC, losndu commented on src/lib/components/ui/ArticleCard.svelte
> +	const styleCache = new Map();
This has been updated accordingly.
My guess, was skipped because "Committable suggestion was skipped due to low confidence."

2024-10-28 06:40 UTC, losndu commented on src/lib/types/article.ts
> +});
Sponsor padding has been removed from the model fields

2024-10-28 06:41 UTC, losndu commented on src/lib/types/article.ts
> +export const paddingRegex = /^(p[txbylr](-[0-9]+)?\s*)+$/;
`sponsor_padding` has been removed from the model field

2024-10-28 17:30 UTC, iankressin commented on src/lib/components/ui/ArticleCard.svelte
> +	const containerClasses = writable<string>('');
writables are svelte 4 way to create global stores. You don't want a store, you want a local state and the way you declare a state in svelte 5 is using`$state`

2024-10-29 16:51 UTC, closed without merging